[versions]
# Java Steam version
javaSteam = "1.3.0"

# Java / Kotlin versions
java = "1.8"
kotlin = "1.9.0"

# Standard Library versions
bouncyCastle = "1.70" # https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on
commons-io = "2.14.0" # https://mvnrepository.com/artifact/commons-io/commons-io
commons-lang3 = "3.13.0" # https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
commons-validator = "1.7" # https://mvnrepository.com/artifact/commons-validator/commons-validator
gson = "2.10.1" # https://mvnrepository.com/artifact/com.google.code.gson/gson
jacoco = "0.8.10" # https://www.eclemma.org/jacoco
javaWebSocket = "1.5.4" # https://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket
kotlin-coroutines = "1.7.3" # https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
okHttp = "4.11.0" # https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
protobuf = "0.9.4" # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-gradle-plugin
protobufJava = "3.23.4" # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
protoc = "3.23.4" # https://mvnrepository.com/artifact/com.google.protobuf/protoc
publishPlugin = "1.1.0" # https://mvnrepository.com/artifact/io.github.gradle-nexus/publish-plugin
qrCode = "1.0.1" # https://mvnrepository.com/artifact/pro.leaco.qrcode/console-qrcode

# Testing Lib versions
commonsCodec = "1.16.0" # https://mvnrepository.com/artifact/commons-codec/commons-codec
jupiterVersion = "5.10.0" # https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
mockWebServer = "5.0.0-alpha.11" # https://mvnrepository.com/artifact/com.squareup.okhttp3/mockwebserver3-junit5
mockitoVersion = "4.11.0" # https://mvnrepository.com/artifact/org.mockito/mockito-core

[libraries]
bouncyCastle = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncyCastle" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commons-validator" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-stdib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }
qrCode = { module = "pro.leaco.qrcode:console-qrcode", version.ref = "qrCode" }
webSocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebSocket" }

test-commonsCodec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
test-jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiterVersion" }
test-jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiterVersion" }
test-jupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiterVersion" }
test-mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockitoVersion" }
test-mockitoJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockitoVersion" }
test-mockwebserver3 = { module = "com.squareup.okhttp3:mockwebserver3-junit5", version.ref = "mockWebServer" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publishPlugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publishPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }

[bundles]
testing = [
    "bouncyCastle",
    "test-commonsCodec",
    "test-jupiterApi",
    "test-jupiterEngine",
    "test-jupiterParams",
    "test-mockitoCore",
    "test-mockitoJupiter",
    "test-mockwebserver3"
]
