// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gcsystemmsgs.proto

package in.dragonbra.javasteam.protobufs.tf;

public final class Gcsystemmsgs {
  private Gcsystemmsgs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code EGCSystemMsg}
   */
  public enum EGCSystemMsg
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EGCMsgInvalid = 0;</code>
     */
    k_EGCMsgInvalid(0),
    /**
     * <code>k_EGCMsgMulti = 1;</code>
     */
    k_EGCMsgMulti(1),
    /**
     * <code>k_EGCMsgGenericReply = 10;</code>
     */
    k_EGCMsgGenericReply(10),
    /**
     * <code>k_EGCMsgSystemBase = 50;</code>
     */
    k_EGCMsgSystemBase(50),
    /**
     * <code>k_EGCMsgAchievementAwarded = 51;</code>
     */
    k_EGCMsgAchievementAwarded(51),
    /**
     * <code>k_EGCMsgConCommand = 52;</code>
     */
    k_EGCMsgConCommand(52),
    /**
     * <code>k_EGCMsgStartPlaying = 53;</code>
     */
    k_EGCMsgStartPlaying(53),
    /**
     * <code>k_EGCMsgStopPlaying = 54;</code>
     */
    k_EGCMsgStopPlaying(54),
    /**
     * <code>k_EGCMsgStartGameserver = 55;</code>
     */
    k_EGCMsgStartGameserver(55),
    /**
     * <code>k_EGCMsgStopGameserver = 56;</code>
     */
    k_EGCMsgStopGameserver(56),
    /**
     * <code>k_EGCMsgWGRequest = 57;</code>
     */
    k_EGCMsgWGRequest(57),
    /**
     * <code>k_EGCMsgWGResponse = 58;</code>
     */
    k_EGCMsgWGResponse(58),
    /**
     * <code>k_EGCMsgGetUserGameStatsSchema = 59;</code>
     */
    k_EGCMsgGetUserGameStatsSchema(59),
    /**
     * <code>k_EGCMsgGetUserGameStatsSchemaResponse = 60;</code>
     */
    k_EGCMsgGetUserGameStatsSchemaResponse(60),
    /**
     * <code>k_EGCMsgGetUserStatsDEPRECATED = 61;</code>
     */
    k_EGCMsgGetUserStatsDEPRECATED(61),
    /**
     * <code>k_EGCMsgGetUserStatsResponse = 62;</code>
     */
    k_EGCMsgGetUserStatsResponse(62),
    /**
     * <code>k_EGCMsgAppInfoUpdated = 63;</code>
     */
    k_EGCMsgAppInfoUpdated(63),
    /**
     * <code>k_EGCMsgValidateSession = 64;</code>
     */
    k_EGCMsgValidateSession(64),
    /**
     * <code>k_EGCMsgValidateSessionResponse = 65;</code>
     */
    k_EGCMsgValidateSessionResponse(65),
    /**
     * <code>k_EGCMsgLookupAccountFromInput = 66;</code>
     */
    k_EGCMsgLookupAccountFromInput(66),
    /**
     * <code>k_EGCMsgSendHTTPRequest = 67;</code>
     */
    k_EGCMsgSendHTTPRequest(67),
    /**
     * <code>k_EGCMsgSendHTTPRequestResponse = 68;</code>
     */
    k_EGCMsgSendHTTPRequestResponse(68),
    /**
     * <code>k_EGCMsgPreTestSetup = 69;</code>
     */
    k_EGCMsgPreTestSetup(69),
    /**
     * <code>k_EGCMsgRecordSupportAction = 70;</code>
     */
    k_EGCMsgRecordSupportAction(70),
    /**
     * <code>k_EGCMsgGetAccountDetails_DEPRECATED = 71;</code>
     */
    k_EGCMsgGetAccountDetails_DEPRECATED(71),
    /**
     * <code>k_EGCMsgReceiveInterAppMessage = 73;</code>
     */
    k_EGCMsgReceiveInterAppMessage(73),
    /**
     * <code>k_EGCMsgFindAccounts = 74;</code>
     */
    k_EGCMsgFindAccounts(74),
    /**
     * <code>k_EGCMsgPostAlert = 75;</code>
     */
    k_EGCMsgPostAlert(75),
    /**
     * <code>k_EGCMsgGetLicenses = 76;</code>
     */
    k_EGCMsgGetLicenses(76),
    /**
     * <code>k_EGCMsgGetUserStats = 77;</code>
     */
    k_EGCMsgGetUserStats(77),
    /**
     * <code>k_EGCMsgGetCommands = 78;</code>
     */
    k_EGCMsgGetCommands(78),
    /**
     * <code>k_EGCMsgGetCommandsResponse = 79;</code>
     */
    k_EGCMsgGetCommandsResponse(79),
    /**
     * <code>k_EGCMsgAddFreeLicense = 80;</code>
     */
    k_EGCMsgAddFreeLicense(80),
    /**
     * <code>k_EGCMsgAddFreeLicenseResponse = 81;</code>
     */
    k_EGCMsgAddFreeLicenseResponse(81),
    /**
     * <code>k_EGCMsgGetIPLocation = 82;</code>
     */
    k_EGCMsgGetIPLocation(82),
    /**
     * <code>k_EGCMsgGetIPLocationResponse = 83;</code>
     */
    k_EGCMsgGetIPLocationResponse(83),
    /**
     * <code>k_EGCMsgSystemStatsSchema = 84;</code>
     */
    k_EGCMsgSystemStatsSchema(84),
    /**
     * <code>k_EGCMsgGetSystemStats = 85;</code>
     */
    k_EGCMsgGetSystemStats(85),
    /**
     * <code>k_EGCMsgGetSystemStatsResponse = 86;</code>
     */
    k_EGCMsgGetSystemStatsResponse(86),
    /**
     * <code>k_EGCMsgSendEmail = 87;</code>
     */
    k_EGCMsgSendEmail(87),
    /**
     * <code>k_EGCMsgSendEmailResponse = 88;</code>
     */
    k_EGCMsgSendEmailResponse(88),
    /**
     * <code>k_EGCMsgGetEmailTemplate = 89;</code>
     */
    k_EGCMsgGetEmailTemplate(89),
    /**
     * <code>k_EGCMsgGetEmailTemplateResponse = 90;</code>
     */
    k_EGCMsgGetEmailTemplateResponse(90),
    /**
     * <code>k_EGCMsgGrantGuestPass = 91;</code>
     */
    k_EGCMsgGrantGuestPass(91),
    /**
     * <code>k_EGCMsgGrantGuestPassResponse = 92;</code>
     */
    k_EGCMsgGrantGuestPassResponse(92),
    /**
     * <code>k_EGCMsgGetAccountDetails = 93;</code>
     */
    k_EGCMsgGetAccountDetails(93),
    /**
     * <code>k_EGCMsgGetAccountDetailsResponse = 94;</code>
     */
    k_EGCMsgGetAccountDetailsResponse(94),
    /**
     * <code>k_EGCMsgGetPersonaNames = 95;</code>
     */
    k_EGCMsgGetPersonaNames(95),
    /**
     * <code>k_EGCMsgGetPersonaNamesResponse = 96;</code>
     */
    k_EGCMsgGetPersonaNamesResponse(96),
    /**
     * <code>k_EGCMsgMultiplexMsg = 97;</code>
     */
    k_EGCMsgMultiplexMsg(97),
    /**
     * <code>k_EGCMsgWebAPIRegisterInterfaces = 101;</code>
     */
    k_EGCMsgWebAPIRegisterInterfaces(101),
    /**
     * <code>k_EGCMsgWebAPIJobRequest = 102;</code>
     */
    k_EGCMsgWebAPIJobRequest(102),
    /**
     * <code>k_EGCMsgWebAPIJobRequestHttpResponse = 104;</code>
     */
    k_EGCMsgWebAPIJobRequestHttpResponse(104),
    /**
     * <code>k_EGCMsgWebAPIJobRequestForwardResponse = 105;</code>
     */
    k_EGCMsgWebAPIJobRequestForwardResponse(105),
    /**
     * <code>k_EGCMsgMemCachedGet = 200;</code>
     */
    k_EGCMsgMemCachedGet(200),
    /**
     * <code>k_EGCMsgMemCachedGetResponse = 201;</code>
     */
    k_EGCMsgMemCachedGetResponse(201),
    /**
     * <code>k_EGCMsgMemCachedSet = 202;</code>
     */
    k_EGCMsgMemCachedSet(202),
    /**
     * <code>k_EGCMsgMemCachedDelete = 203;</code>
     */
    k_EGCMsgMemCachedDelete(203),
    /**
     * <code>k_EGCMsgMemCachedStats = 204;</code>
     */
    k_EGCMsgMemCachedStats(204),
    /**
     * <code>k_EGCMsgMemCachedStatsResponse = 205;</code>
     */
    k_EGCMsgMemCachedStatsResponse(205),
    /**
     * <code>k_EGCMsgSQLStats = 210;</code>
     */
    k_EGCMsgSQLStats(210),
    /**
     * <code>k_EGCMsgSQLStatsResponse = 211;</code>
     */
    k_EGCMsgSQLStatsResponse(211),
    /**
     * <code>k_EGCMsgMasterSetDirectory = 220;</code>
     */
    k_EGCMsgMasterSetDirectory(220),
    /**
     * <code>k_EGCMsgMasterSetDirectoryResponse = 221;</code>
     */
    k_EGCMsgMasterSetDirectoryResponse(221),
    /**
     * <code>k_EGCMsgMasterSetWebAPIRouting = 222;</code>
     */
    k_EGCMsgMasterSetWebAPIRouting(222),
    /**
     * <code>k_EGCMsgMasterSetWebAPIRoutingResponse = 223;</code>
     */
    k_EGCMsgMasterSetWebAPIRoutingResponse(223),
    /**
     * <code>k_EGCMsgMasterSetClientMsgRouting = 224;</code>
     */
    k_EGCMsgMasterSetClientMsgRouting(224),
    /**
     * <code>k_EGCMsgMasterSetClientMsgRoutingResponse = 225;</code>
     */
    k_EGCMsgMasterSetClientMsgRoutingResponse(225),
    /**
     * <code>k_EGCMsgSetOptions = 226;</code>
     */
    k_EGCMsgSetOptions(226),
    /**
     * <code>k_EGCMsgSetOptionsResponse = 227;</code>
     */
    k_EGCMsgSetOptionsResponse(227),
    /**
     * <code>k_EGCMsgSystemBase2 = 500;</code>
     */
    k_EGCMsgSystemBase2(500),
    /**
     * <code>k_EGCMsgGetPurchaseTrustStatus = 501;</code>
     */
    k_EGCMsgGetPurchaseTrustStatus(501),
    /**
     * <code>k_EGCMsgGetPurchaseTrustStatusResponse = 502;</code>
     */
    k_EGCMsgGetPurchaseTrustStatusResponse(502),
    /**
     * <code>k_EGCMsgUpdateSession = 503;</code>
     */
    k_EGCMsgUpdateSession(503),
    /**
     * <code>k_EGCMsgGCAccountVacStatusChange = 504;</code>
     */
    k_EGCMsgGCAccountVacStatusChange(504),
    /**
     * <code>k_EGCMsgCheckFriendship = 505;</code>
     */
    k_EGCMsgCheckFriendship(505),
    /**
     * <code>k_EGCMsgCheckFriendshipResponse = 506;</code>
     */
    k_EGCMsgCheckFriendshipResponse(506),
    /**
     * <code>k_EGCMsgGetPartnerAccountLink = 507;</code>
     */
    k_EGCMsgGetPartnerAccountLink(507),
    /**
     * <code>k_EGCMsgGetPartnerAccountLinkResponse = 508;</code>
     */
    k_EGCMsgGetPartnerAccountLinkResponse(508),
    /**
     * <code>k_EGCMsgVSReportedSuspiciousActivity = 509;</code>
     */
    k_EGCMsgVSReportedSuspiciousActivity(509),
    /**
     * <code>k_EGCMsgAccountTradeBanStatusChange = 510;</code>
     */
    k_EGCMsgAccountTradeBanStatusChange(510),
    /**
     * <code>k_EGCMsgAccountLockStatusChange = 511;</code>
     */
    k_EGCMsgAccountLockStatusChange(511),
    /**
     * <code>k_EGCMsgDPPartnerMicroTxns = 512;</code>
     */
    k_EGCMsgDPPartnerMicroTxns(512),
    /**
     * <code>k_EGCMsgDPPartnerMicroTxnsResponse = 513;</code>
     */
    k_EGCMsgDPPartnerMicroTxnsResponse(513),
    /**
     * <code>k_EGCMsgGetIPASN = 514;</code>
     */
    k_EGCMsgGetIPASN(514),
    /**
     * <code>k_EGCMsgGetIPASNResponse = 515;</code>
     */
    k_EGCMsgGetIPASNResponse(515),
    /**
     * <code>k_EGCMsgGetAppFriendsList = 516;</code>
     */
    k_EGCMsgGetAppFriendsList(516),
    /**
     * <code>k_EGCMsgGetAppFriendsListResponse = 517;</code>
     */
    k_EGCMsgGetAppFriendsListResponse(517),
    /**
     * <code>k_EGCMsgVacVerificationChange = 518;</code>
     */
    k_EGCMsgVacVerificationChange(518),
    /**
     * <code>k_EGCMsgAccountPhoneNumberChange = 519;</code>
     */
    k_EGCMsgAccountPhoneNumberChange(519),
    /**
     * <code>k_EGCMsgAccountTwoFactorChange = 520;</code>
     */
    k_EGCMsgAccountTwoFactorChange(520),
    /**
     * <code>k_EGCMsgCheckClanMembership = 521;</code>
     */
    k_EGCMsgCheckClanMembership(521),
    /**
     * <code>k_EGCMsgCheckClanMembershipResponse = 522;</code>
     */
    k_EGCMsgCheckClanMembershipResponse(522),
    ;

    /**
     * <code>k_EGCMsgInvalid = 0;</code>
     */
    public static final int k_EGCMsgInvalid_VALUE = 0;
    /**
     * <code>k_EGCMsgMulti = 1;</code>
     */
    public static final int k_EGCMsgMulti_VALUE = 1;
    /**
     * <code>k_EGCMsgGenericReply = 10;</code>
     */
    public static final int k_EGCMsgGenericReply_VALUE = 10;
    /**
     * <code>k_EGCMsgSystemBase = 50;</code>
     */
    public static final int k_EGCMsgSystemBase_VALUE = 50;
    /**
     * <code>k_EGCMsgAchievementAwarded = 51;</code>
     */
    public static final int k_EGCMsgAchievementAwarded_VALUE = 51;
    /**
     * <code>k_EGCMsgConCommand = 52;</code>
     */
    public static final int k_EGCMsgConCommand_VALUE = 52;
    /**
     * <code>k_EGCMsgStartPlaying = 53;</code>
     */
    public static final int k_EGCMsgStartPlaying_VALUE = 53;
    /**
     * <code>k_EGCMsgStopPlaying = 54;</code>
     */
    public static final int k_EGCMsgStopPlaying_VALUE = 54;
    /**
     * <code>k_EGCMsgStartGameserver = 55;</code>
     */
    public static final int k_EGCMsgStartGameserver_VALUE = 55;
    /**
     * <code>k_EGCMsgStopGameserver = 56;</code>
     */
    public static final int k_EGCMsgStopGameserver_VALUE = 56;
    /**
     * <code>k_EGCMsgWGRequest = 57;</code>
     */
    public static final int k_EGCMsgWGRequest_VALUE = 57;
    /**
     * <code>k_EGCMsgWGResponse = 58;</code>
     */
    public static final int k_EGCMsgWGResponse_VALUE = 58;
    /**
     * <code>k_EGCMsgGetUserGameStatsSchema = 59;</code>
     */
    public static final int k_EGCMsgGetUserGameStatsSchema_VALUE = 59;
    /**
     * <code>k_EGCMsgGetUserGameStatsSchemaResponse = 60;</code>
     */
    public static final int k_EGCMsgGetUserGameStatsSchemaResponse_VALUE = 60;
    /**
     * <code>k_EGCMsgGetUserStatsDEPRECATED = 61;</code>
     */
    public static final int k_EGCMsgGetUserStatsDEPRECATED_VALUE = 61;
    /**
     * <code>k_EGCMsgGetUserStatsResponse = 62;</code>
     */
    public static final int k_EGCMsgGetUserStatsResponse_VALUE = 62;
    /**
     * <code>k_EGCMsgAppInfoUpdated = 63;</code>
     */
    public static final int k_EGCMsgAppInfoUpdated_VALUE = 63;
    /**
     * <code>k_EGCMsgValidateSession = 64;</code>
     */
    public static final int k_EGCMsgValidateSession_VALUE = 64;
    /**
     * <code>k_EGCMsgValidateSessionResponse = 65;</code>
     */
    public static final int k_EGCMsgValidateSessionResponse_VALUE = 65;
    /**
     * <code>k_EGCMsgLookupAccountFromInput = 66;</code>
     */
    public static final int k_EGCMsgLookupAccountFromInput_VALUE = 66;
    /**
     * <code>k_EGCMsgSendHTTPRequest = 67;</code>
     */
    public static final int k_EGCMsgSendHTTPRequest_VALUE = 67;
    /**
     * <code>k_EGCMsgSendHTTPRequestResponse = 68;</code>
     */
    public static final int k_EGCMsgSendHTTPRequestResponse_VALUE = 68;
    /**
     * <code>k_EGCMsgPreTestSetup = 69;</code>
     */
    public static final int k_EGCMsgPreTestSetup_VALUE = 69;
    /**
     * <code>k_EGCMsgRecordSupportAction = 70;</code>
     */
    public static final int k_EGCMsgRecordSupportAction_VALUE = 70;
    /**
     * <code>k_EGCMsgGetAccountDetails_DEPRECATED = 71;</code>
     */
    public static final int k_EGCMsgGetAccountDetails_DEPRECATED_VALUE = 71;
    /**
     * <code>k_EGCMsgReceiveInterAppMessage = 73;</code>
     */
    public static final int k_EGCMsgReceiveInterAppMessage_VALUE = 73;
    /**
     * <code>k_EGCMsgFindAccounts = 74;</code>
     */
    public static final int k_EGCMsgFindAccounts_VALUE = 74;
    /**
     * <code>k_EGCMsgPostAlert = 75;</code>
     */
    public static final int k_EGCMsgPostAlert_VALUE = 75;
    /**
     * <code>k_EGCMsgGetLicenses = 76;</code>
     */
    public static final int k_EGCMsgGetLicenses_VALUE = 76;
    /**
     * <code>k_EGCMsgGetUserStats = 77;</code>
     */
    public static final int k_EGCMsgGetUserStats_VALUE = 77;
    /**
     * <code>k_EGCMsgGetCommands = 78;</code>
     */
    public static final int k_EGCMsgGetCommands_VALUE = 78;
    /**
     * <code>k_EGCMsgGetCommandsResponse = 79;</code>
     */
    public static final int k_EGCMsgGetCommandsResponse_VALUE = 79;
    /**
     * <code>k_EGCMsgAddFreeLicense = 80;</code>
     */
    public static final int k_EGCMsgAddFreeLicense_VALUE = 80;
    /**
     * <code>k_EGCMsgAddFreeLicenseResponse = 81;</code>
     */
    public static final int k_EGCMsgAddFreeLicenseResponse_VALUE = 81;
    /**
     * <code>k_EGCMsgGetIPLocation = 82;</code>
     */
    public static final int k_EGCMsgGetIPLocation_VALUE = 82;
    /**
     * <code>k_EGCMsgGetIPLocationResponse = 83;</code>
     */
    public static final int k_EGCMsgGetIPLocationResponse_VALUE = 83;
    /**
     * <code>k_EGCMsgSystemStatsSchema = 84;</code>
     */
    public static final int k_EGCMsgSystemStatsSchema_VALUE = 84;
    /**
     * <code>k_EGCMsgGetSystemStats = 85;</code>
     */
    public static final int k_EGCMsgGetSystemStats_VALUE = 85;
    /**
     * <code>k_EGCMsgGetSystemStatsResponse = 86;</code>
     */
    public static final int k_EGCMsgGetSystemStatsResponse_VALUE = 86;
    /**
     * <code>k_EGCMsgSendEmail = 87;</code>
     */
    public static final int k_EGCMsgSendEmail_VALUE = 87;
    /**
     * <code>k_EGCMsgSendEmailResponse = 88;</code>
     */
    public static final int k_EGCMsgSendEmailResponse_VALUE = 88;
    /**
     * <code>k_EGCMsgGetEmailTemplate = 89;</code>
     */
    public static final int k_EGCMsgGetEmailTemplate_VALUE = 89;
    /**
     * <code>k_EGCMsgGetEmailTemplateResponse = 90;</code>
     */
    public static final int k_EGCMsgGetEmailTemplateResponse_VALUE = 90;
    /**
     * <code>k_EGCMsgGrantGuestPass = 91;</code>
     */
    public static final int k_EGCMsgGrantGuestPass_VALUE = 91;
    /**
     * <code>k_EGCMsgGrantGuestPassResponse = 92;</code>
     */
    public static final int k_EGCMsgGrantGuestPassResponse_VALUE = 92;
    /**
     * <code>k_EGCMsgGetAccountDetails = 93;</code>
     */
    public static final int k_EGCMsgGetAccountDetails_VALUE = 93;
    /**
     * <code>k_EGCMsgGetAccountDetailsResponse = 94;</code>
     */
    public static final int k_EGCMsgGetAccountDetailsResponse_VALUE = 94;
    /**
     * <code>k_EGCMsgGetPersonaNames = 95;</code>
     */
    public static final int k_EGCMsgGetPersonaNames_VALUE = 95;
    /**
     * <code>k_EGCMsgGetPersonaNamesResponse = 96;</code>
     */
    public static final int k_EGCMsgGetPersonaNamesResponse_VALUE = 96;
    /**
     * <code>k_EGCMsgMultiplexMsg = 97;</code>
     */
    public static final int k_EGCMsgMultiplexMsg_VALUE = 97;
    /**
     * <code>k_EGCMsgWebAPIRegisterInterfaces = 101;</code>
     */
    public static final int k_EGCMsgWebAPIRegisterInterfaces_VALUE = 101;
    /**
     * <code>k_EGCMsgWebAPIJobRequest = 102;</code>
     */
    public static final int k_EGCMsgWebAPIJobRequest_VALUE = 102;
    /**
     * <code>k_EGCMsgWebAPIJobRequestHttpResponse = 104;</code>
     */
    public static final int k_EGCMsgWebAPIJobRequestHttpResponse_VALUE = 104;
    /**
     * <code>k_EGCMsgWebAPIJobRequestForwardResponse = 105;</code>
     */
    public static final int k_EGCMsgWebAPIJobRequestForwardResponse_VALUE = 105;
    /**
     * <code>k_EGCMsgMemCachedGet = 200;</code>
     */
    public static final int k_EGCMsgMemCachedGet_VALUE = 200;
    /**
     * <code>k_EGCMsgMemCachedGetResponse = 201;</code>
     */
    public static final int k_EGCMsgMemCachedGetResponse_VALUE = 201;
    /**
     * <code>k_EGCMsgMemCachedSet = 202;</code>
     */
    public static final int k_EGCMsgMemCachedSet_VALUE = 202;
    /**
     * <code>k_EGCMsgMemCachedDelete = 203;</code>
     */
    public static final int k_EGCMsgMemCachedDelete_VALUE = 203;
    /**
     * <code>k_EGCMsgMemCachedStats = 204;</code>
     */
    public static final int k_EGCMsgMemCachedStats_VALUE = 204;
    /**
     * <code>k_EGCMsgMemCachedStatsResponse = 205;</code>
     */
    public static final int k_EGCMsgMemCachedStatsResponse_VALUE = 205;
    /**
     * <code>k_EGCMsgSQLStats = 210;</code>
     */
    public static final int k_EGCMsgSQLStats_VALUE = 210;
    /**
     * <code>k_EGCMsgSQLStatsResponse = 211;</code>
     */
    public static final int k_EGCMsgSQLStatsResponse_VALUE = 211;
    /**
     * <code>k_EGCMsgMasterSetDirectory = 220;</code>
     */
    public static final int k_EGCMsgMasterSetDirectory_VALUE = 220;
    /**
     * <code>k_EGCMsgMasterSetDirectoryResponse = 221;</code>
     */
    public static final int k_EGCMsgMasterSetDirectoryResponse_VALUE = 221;
    /**
     * <code>k_EGCMsgMasterSetWebAPIRouting = 222;</code>
     */
    public static final int k_EGCMsgMasterSetWebAPIRouting_VALUE = 222;
    /**
     * <code>k_EGCMsgMasterSetWebAPIRoutingResponse = 223;</code>
     */
    public static final int k_EGCMsgMasterSetWebAPIRoutingResponse_VALUE = 223;
    /**
     * <code>k_EGCMsgMasterSetClientMsgRouting = 224;</code>
     */
    public static final int k_EGCMsgMasterSetClientMsgRouting_VALUE = 224;
    /**
     * <code>k_EGCMsgMasterSetClientMsgRoutingResponse = 225;</code>
     */
    public static final int k_EGCMsgMasterSetClientMsgRoutingResponse_VALUE = 225;
    /**
     * <code>k_EGCMsgSetOptions = 226;</code>
     */
    public static final int k_EGCMsgSetOptions_VALUE = 226;
    /**
     * <code>k_EGCMsgSetOptionsResponse = 227;</code>
     */
    public static final int k_EGCMsgSetOptionsResponse_VALUE = 227;
    /**
     * <code>k_EGCMsgSystemBase2 = 500;</code>
     */
    public static final int k_EGCMsgSystemBase2_VALUE = 500;
    /**
     * <code>k_EGCMsgGetPurchaseTrustStatus = 501;</code>
     */
    public static final int k_EGCMsgGetPurchaseTrustStatus_VALUE = 501;
    /**
     * <code>k_EGCMsgGetPurchaseTrustStatusResponse = 502;</code>
     */
    public static final int k_EGCMsgGetPurchaseTrustStatusResponse_VALUE = 502;
    /**
     * <code>k_EGCMsgUpdateSession = 503;</code>
     */
    public static final int k_EGCMsgUpdateSession_VALUE = 503;
    /**
     * <code>k_EGCMsgGCAccountVacStatusChange = 504;</code>
     */
    public static final int k_EGCMsgGCAccountVacStatusChange_VALUE = 504;
    /**
     * <code>k_EGCMsgCheckFriendship = 505;</code>
     */
    public static final int k_EGCMsgCheckFriendship_VALUE = 505;
    /**
     * <code>k_EGCMsgCheckFriendshipResponse = 506;</code>
     */
    public static final int k_EGCMsgCheckFriendshipResponse_VALUE = 506;
    /**
     * <code>k_EGCMsgGetPartnerAccountLink = 507;</code>
     */
    public static final int k_EGCMsgGetPartnerAccountLink_VALUE = 507;
    /**
     * <code>k_EGCMsgGetPartnerAccountLinkResponse = 508;</code>
     */
    public static final int k_EGCMsgGetPartnerAccountLinkResponse_VALUE = 508;
    /**
     * <code>k_EGCMsgVSReportedSuspiciousActivity = 509;</code>
     */
    public static final int k_EGCMsgVSReportedSuspiciousActivity_VALUE = 509;
    /**
     * <code>k_EGCMsgAccountTradeBanStatusChange = 510;</code>
     */
    public static final int k_EGCMsgAccountTradeBanStatusChange_VALUE = 510;
    /**
     * <code>k_EGCMsgAccountLockStatusChange = 511;</code>
     */
    public static final int k_EGCMsgAccountLockStatusChange_VALUE = 511;
    /**
     * <code>k_EGCMsgDPPartnerMicroTxns = 512;</code>
     */
    public static final int k_EGCMsgDPPartnerMicroTxns_VALUE = 512;
    /**
     * <code>k_EGCMsgDPPartnerMicroTxnsResponse = 513;</code>
     */
    public static final int k_EGCMsgDPPartnerMicroTxnsResponse_VALUE = 513;
    /**
     * <code>k_EGCMsgGetIPASN = 514;</code>
     */
    public static final int k_EGCMsgGetIPASN_VALUE = 514;
    /**
     * <code>k_EGCMsgGetIPASNResponse = 515;</code>
     */
    public static final int k_EGCMsgGetIPASNResponse_VALUE = 515;
    /**
     * <code>k_EGCMsgGetAppFriendsList = 516;</code>
     */
    public static final int k_EGCMsgGetAppFriendsList_VALUE = 516;
    /**
     * <code>k_EGCMsgGetAppFriendsListResponse = 517;</code>
     */
    public static final int k_EGCMsgGetAppFriendsListResponse_VALUE = 517;
    /**
     * <code>k_EGCMsgVacVerificationChange = 518;</code>
     */
    public static final int k_EGCMsgVacVerificationChange_VALUE = 518;
    /**
     * <code>k_EGCMsgAccountPhoneNumberChange = 519;</code>
     */
    public static final int k_EGCMsgAccountPhoneNumberChange_VALUE = 519;
    /**
     * <code>k_EGCMsgAccountTwoFactorChange = 520;</code>
     */
    public static final int k_EGCMsgAccountTwoFactorChange_VALUE = 520;
    /**
     * <code>k_EGCMsgCheckClanMembership = 521;</code>
     */
    public static final int k_EGCMsgCheckClanMembership_VALUE = 521;
    /**
     * <code>k_EGCMsgCheckClanMembershipResponse = 522;</code>
     */
    public static final int k_EGCMsgCheckClanMembershipResponse_VALUE = 522;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EGCSystemMsg valueOf(int value) {
      return forNumber(value);
    }

    public static EGCSystemMsg forNumber(int value) {
      switch (value) {
        case 0: return k_EGCMsgInvalid;
        case 1: return k_EGCMsgMulti;
        case 10: return k_EGCMsgGenericReply;
        case 50: return k_EGCMsgSystemBase;
        case 51: return k_EGCMsgAchievementAwarded;
        case 52: return k_EGCMsgConCommand;
        case 53: return k_EGCMsgStartPlaying;
        case 54: return k_EGCMsgStopPlaying;
        case 55: return k_EGCMsgStartGameserver;
        case 56: return k_EGCMsgStopGameserver;
        case 57: return k_EGCMsgWGRequest;
        case 58: return k_EGCMsgWGResponse;
        case 59: return k_EGCMsgGetUserGameStatsSchema;
        case 60: return k_EGCMsgGetUserGameStatsSchemaResponse;
        case 61: return k_EGCMsgGetUserStatsDEPRECATED;
        case 62: return k_EGCMsgGetUserStatsResponse;
        case 63: return k_EGCMsgAppInfoUpdated;
        case 64: return k_EGCMsgValidateSession;
        case 65: return k_EGCMsgValidateSessionResponse;
        case 66: return k_EGCMsgLookupAccountFromInput;
        case 67: return k_EGCMsgSendHTTPRequest;
        case 68: return k_EGCMsgSendHTTPRequestResponse;
        case 69: return k_EGCMsgPreTestSetup;
        case 70: return k_EGCMsgRecordSupportAction;
        case 71: return k_EGCMsgGetAccountDetails_DEPRECATED;
        case 73: return k_EGCMsgReceiveInterAppMessage;
        case 74: return k_EGCMsgFindAccounts;
        case 75: return k_EGCMsgPostAlert;
        case 76: return k_EGCMsgGetLicenses;
        case 77: return k_EGCMsgGetUserStats;
        case 78: return k_EGCMsgGetCommands;
        case 79: return k_EGCMsgGetCommandsResponse;
        case 80: return k_EGCMsgAddFreeLicense;
        case 81: return k_EGCMsgAddFreeLicenseResponse;
        case 82: return k_EGCMsgGetIPLocation;
        case 83: return k_EGCMsgGetIPLocationResponse;
        case 84: return k_EGCMsgSystemStatsSchema;
        case 85: return k_EGCMsgGetSystemStats;
        case 86: return k_EGCMsgGetSystemStatsResponse;
        case 87: return k_EGCMsgSendEmail;
        case 88: return k_EGCMsgSendEmailResponse;
        case 89: return k_EGCMsgGetEmailTemplate;
        case 90: return k_EGCMsgGetEmailTemplateResponse;
        case 91: return k_EGCMsgGrantGuestPass;
        case 92: return k_EGCMsgGrantGuestPassResponse;
        case 93: return k_EGCMsgGetAccountDetails;
        case 94: return k_EGCMsgGetAccountDetailsResponse;
        case 95: return k_EGCMsgGetPersonaNames;
        case 96: return k_EGCMsgGetPersonaNamesResponse;
        case 97: return k_EGCMsgMultiplexMsg;
        case 101: return k_EGCMsgWebAPIRegisterInterfaces;
        case 102: return k_EGCMsgWebAPIJobRequest;
        case 104: return k_EGCMsgWebAPIJobRequestHttpResponse;
        case 105: return k_EGCMsgWebAPIJobRequestForwardResponse;
        case 200: return k_EGCMsgMemCachedGet;
        case 201: return k_EGCMsgMemCachedGetResponse;
        case 202: return k_EGCMsgMemCachedSet;
        case 203: return k_EGCMsgMemCachedDelete;
        case 204: return k_EGCMsgMemCachedStats;
        case 205: return k_EGCMsgMemCachedStatsResponse;
        case 210: return k_EGCMsgSQLStats;
        case 211: return k_EGCMsgSQLStatsResponse;
        case 220: return k_EGCMsgMasterSetDirectory;
        case 221: return k_EGCMsgMasterSetDirectoryResponse;
        case 222: return k_EGCMsgMasterSetWebAPIRouting;
        case 223: return k_EGCMsgMasterSetWebAPIRoutingResponse;
        case 224: return k_EGCMsgMasterSetClientMsgRouting;
        case 225: return k_EGCMsgMasterSetClientMsgRoutingResponse;
        case 226: return k_EGCMsgSetOptions;
        case 227: return k_EGCMsgSetOptionsResponse;
        case 500: return k_EGCMsgSystemBase2;
        case 501: return k_EGCMsgGetPurchaseTrustStatus;
        case 502: return k_EGCMsgGetPurchaseTrustStatusResponse;
        case 503: return k_EGCMsgUpdateSession;
        case 504: return k_EGCMsgGCAccountVacStatusChange;
        case 505: return k_EGCMsgCheckFriendship;
        case 506: return k_EGCMsgCheckFriendshipResponse;
        case 507: return k_EGCMsgGetPartnerAccountLink;
        case 508: return k_EGCMsgGetPartnerAccountLinkResponse;
        case 509: return k_EGCMsgVSReportedSuspiciousActivity;
        case 510: return k_EGCMsgAccountTradeBanStatusChange;
        case 511: return k_EGCMsgAccountLockStatusChange;
        case 512: return k_EGCMsgDPPartnerMicroTxns;
        case 513: return k_EGCMsgDPPartnerMicroTxnsResponse;
        case 514: return k_EGCMsgGetIPASN;
        case 515: return k_EGCMsgGetIPASNResponse;
        case 516: return k_EGCMsgGetAppFriendsList;
        case 517: return k_EGCMsgGetAppFriendsListResponse;
        case 518: return k_EGCMsgVacVerificationChange;
        case 519: return k_EGCMsgAccountPhoneNumberChange;
        case 520: return k_EGCMsgAccountTwoFactorChange;
        case 521: return k_EGCMsgCheckClanMembership;
        case 522: return k_EGCMsgCheckClanMembershipResponse;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EGCSystemMsg>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EGCSystemMsg> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EGCSystemMsg>() {
            public EGCSystemMsg findValueByNumber(int number) {
              return EGCSystemMsg.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return in.dragonbra.javasteam.protobufs.tf.Gcsystemmsgs.getDescriptor().getEnumTypes().get(0);
    }

    private static final EGCSystemMsg[] VALUES = values();

    public static EGCSystemMsg valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EGCSystemMsg(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EGCSystemMsg)
  }

  /**
   * Protobuf enum {@code ESOMsg}
   */
  public enum ESOMsg
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_ESOMsg_Create = 21;</code>
     */
    k_ESOMsg_Create(21),
    /**
     * <code>k_ESOMsg_Update = 22;</code>
     */
    k_ESOMsg_Update(22),
    /**
     * <code>k_ESOMsg_Destroy = 23;</code>
     */
    k_ESOMsg_Destroy(23),
    /**
     * <code>k_ESOMsg_CacheSubscribed = 24;</code>
     */
    k_ESOMsg_CacheSubscribed(24),
    /**
     * <code>k_ESOMsg_CacheUnsubscribed = 25;</code>
     */
    k_ESOMsg_CacheUnsubscribed(25),
    /**
     * <code>k_ESOMsg_UpdateMultiple = 26;</code>
     */
    k_ESOMsg_UpdateMultiple(26),
    /**
     * <code>k_ESOMsg_CacheSubscriptionCheck = 27;</code>
     */
    k_ESOMsg_CacheSubscriptionCheck(27),
    /**
     * <code>k_ESOMsg_CacheSubscriptionRefresh = 28;</code>
     */
    k_ESOMsg_CacheSubscriptionRefresh(28),
    /**
     * <code>k_ESOMsg_CacheSubscribedUpToDate = 29;</code>
     */
    k_ESOMsg_CacheSubscribedUpToDate(29),
    ;

    /**
     * <code>k_ESOMsg_Create = 21;</code>
     */
    public static final int k_ESOMsg_Create_VALUE = 21;
    /**
     * <code>k_ESOMsg_Update = 22;</code>
     */
    public static final int k_ESOMsg_Update_VALUE = 22;
    /**
     * <code>k_ESOMsg_Destroy = 23;</code>
     */
    public static final int k_ESOMsg_Destroy_VALUE = 23;
    /**
     * <code>k_ESOMsg_CacheSubscribed = 24;</code>
     */
    public static final int k_ESOMsg_CacheSubscribed_VALUE = 24;
    /**
     * <code>k_ESOMsg_CacheUnsubscribed = 25;</code>
     */
    public static final int k_ESOMsg_CacheUnsubscribed_VALUE = 25;
    /**
     * <code>k_ESOMsg_UpdateMultiple = 26;</code>
     */
    public static final int k_ESOMsg_UpdateMultiple_VALUE = 26;
    /**
     * <code>k_ESOMsg_CacheSubscriptionCheck = 27;</code>
     */
    public static final int k_ESOMsg_CacheSubscriptionCheck_VALUE = 27;
    /**
     * <code>k_ESOMsg_CacheSubscriptionRefresh = 28;</code>
     */
    public static final int k_ESOMsg_CacheSubscriptionRefresh_VALUE = 28;
    /**
     * <code>k_ESOMsg_CacheSubscribedUpToDate = 29;</code>
     */
    public static final int k_ESOMsg_CacheSubscribedUpToDate_VALUE = 29;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ESOMsg valueOf(int value) {
      return forNumber(value);
    }

    public static ESOMsg forNumber(int value) {
      switch (value) {
        case 21: return k_ESOMsg_Create;
        case 22: return k_ESOMsg_Update;
        case 23: return k_ESOMsg_Destroy;
        case 24: return k_ESOMsg_CacheSubscribed;
        case 25: return k_ESOMsg_CacheUnsubscribed;
        case 26: return k_ESOMsg_UpdateMultiple;
        case 27: return k_ESOMsg_CacheSubscriptionCheck;
        case 28: return k_ESOMsg_CacheSubscriptionRefresh;
        case 29: return k_ESOMsg_CacheSubscribedUpToDate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ESOMsg>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ESOMsg> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ESOMsg>() {
            public ESOMsg findValueByNumber(int number) {
              return ESOMsg.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return in.dragonbra.javasteam.protobufs.tf.Gcsystemmsgs.getDescriptor().getEnumTypes().get(1);
    }

    private static final ESOMsg[] VALUES = values();

    public static ESOMsg valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ESOMsg(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ESOMsg)
  }

  /**
   * Protobuf enum {@code EGCBaseClientMsg}
   */
  public enum EGCBaseClientMsg
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EMsgGCPingRequest = 3001;</code>
     */
    k_EMsgGCPingRequest(3001),
    /**
     * <code>k_EMsgGCPingResponse = 3002;</code>
     */
    k_EMsgGCPingResponse(3002),
    /**
     * <code>k_EMsgGCClientWelcome = 4004;</code>
     */
    k_EMsgGCClientWelcome(4004),
    /**
     * <code>k_EMsgGCServerWelcome = 4005;</code>
     */
    k_EMsgGCServerWelcome(4005),
    /**
     * <code>k_EMsgGCClientHello = 4006;</code>
     */
    k_EMsgGCClientHello(4006),
    /**
     * <code>k_EMsgGCServerHello = 4007;</code>
     */
    k_EMsgGCServerHello(4007),
    /**
     * <code>k_EMsgGCClientGoodbye = 4008;</code>
     */
    k_EMsgGCClientGoodbye(4008),
    /**
     * <code>k_EMsgGCServerGoodbye = 4009;</code>
     */
    k_EMsgGCServerGoodbye(4009),
    ;

    /**
     * <code>k_EMsgGCPingRequest = 3001;</code>
     */
    public static final int k_EMsgGCPingRequest_VALUE = 3001;
    /**
     * <code>k_EMsgGCPingResponse = 3002;</code>
     */
    public static final int k_EMsgGCPingResponse_VALUE = 3002;
    /**
     * <code>k_EMsgGCClientWelcome = 4004;</code>
     */
    public static final int k_EMsgGCClientWelcome_VALUE = 4004;
    /**
     * <code>k_EMsgGCServerWelcome = 4005;</code>
     */
    public static final int k_EMsgGCServerWelcome_VALUE = 4005;
    /**
     * <code>k_EMsgGCClientHello = 4006;</code>
     */
    public static final int k_EMsgGCClientHello_VALUE = 4006;
    /**
     * <code>k_EMsgGCServerHello = 4007;</code>
     */
    public static final int k_EMsgGCServerHello_VALUE = 4007;
    /**
     * <code>k_EMsgGCClientGoodbye = 4008;</code>
     */
    public static final int k_EMsgGCClientGoodbye_VALUE = 4008;
    /**
     * <code>k_EMsgGCServerGoodbye = 4009;</code>
     */
    public static final int k_EMsgGCServerGoodbye_VALUE = 4009;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EGCBaseClientMsg valueOf(int value) {
      return forNumber(value);
    }

    public static EGCBaseClientMsg forNumber(int value) {
      switch (value) {
        case 3001: return k_EMsgGCPingRequest;
        case 3002: return k_EMsgGCPingResponse;
        case 4004: return k_EMsgGCClientWelcome;
        case 4005: return k_EMsgGCServerWelcome;
        case 4006: return k_EMsgGCClientHello;
        case 4007: return k_EMsgGCServerHello;
        case 4008: return k_EMsgGCClientGoodbye;
        case 4009: return k_EMsgGCServerGoodbye;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EGCBaseClientMsg>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EGCBaseClientMsg> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EGCBaseClientMsg>() {
            public EGCBaseClientMsg findValueByNumber(int number) {
              return EGCBaseClientMsg.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return in.dragonbra.javasteam.protobufs.tf.Gcsystemmsgs.getDescriptor().getEnumTypes().get(2);
    }

    private static final EGCBaseClientMsg[] VALUES = values();

    public static EGCBaseClientMsg valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EGCBaseClientMsg(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EGCBaseClientMsg)
  }

  /**
   * Protobuf enum {@code EGCToGCMsg}
   */
  public enum EGCToGCMsg
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EGCToGCMsgMasterAck = 150;</code>
     */
    k_EGCToGCMsgMasterAck(150),
    /**
     * <code>k_EGCToGCMsgMasterAckResponse = 151;</code>
     */
    k_EGCToGCMsgMasterAckResponse(151),
    /**
     * <code>k_EGCToGCMsgRouted = 152;</code>
     */
    k_EGCToGCMsgRouted(152),
    /**
     * <code>k_EGCToGCMsgRoutedReply = 153;</code>
     */
    k_EGCToGCMsgRoutedReply(153),
    /**
     * <code>k_EMsgGCUpdateSubGCSessionInfo = 154;</code>
     */
    k_EMsgGCUpdateSubGCSessionInfo(154),
    /**
     * <code>k_EMsgGCRequestSubGCSessionInfo = 155;</code>
     */
    k_EMsgGCRequestSubGCSessionInfo(155),
    /**
     * <code>k_EMsgGCRequestSubGCSessionInfoResponse = 156;</code>
     */
    k_EMsgGCRequestSubGCSessionInfoResponse(156),
    /**
     * <code>k_EGCToGCMsgMasterStartupComplete = 157;</code>
     */
    k_EGCToGCMsgMasterStartupComplete(157),
    /**
     * <code>k_EMsgGCToGCSOCacheSubscribe = 158;</code>
     */
    k_EMsgGCToGCSOCacheSubscribe(158),
    /**
     * <code>k_EMsgGCToGCSOCacheUnsubscribe = 159;</code>
     */
    k_EMsgGCToGCSOCacheUnsubscribe(159),
    ;

    /**
     * <code>k_EGCToGCMsgMasterAck = 150;</code>
     */
    public static final int k_EGCToGCMsgMasterAck_VALUE = 150;
    /**
     * <code>k_EGCToGCMsgMasterAckResponse = 151;</code>
     */
    public static final int k_EGCToGCMsgMasterAckResponse_VALUE = 151;
    /**
     * <code>k_EGCToGCMsgRouted = 152;</code>
     */
    public static final int k_EGCToGCMsgRouted_VALUE = 152;
    /**
     * <code>k_EGCToGCMsgRoutedReply = 153;</code>
     */
    public static final int k_EGCToGCMsgRoutedReply_VALUE = 153;
    /**
     * <code>k_EMsgGCUpdateSubGCSessionInfo = 154;</code>
     */
    public static final int k_EMsgGCUpdateSubGCSessionInfo_VALUE = 154;
    /**
     * <code>k_EMsgGCRequestSubGCSessionInfo = 155;</code>
     */
    public static final int k_EMsgGCRequestSubGCSessionInfo_VALUE = 155;
    /**
     * <code>k_EMsgGCRequestSubGCSessionInfoResponse = 156;</code>
     */
    public static final int k_EMsgGCRequestSubGCSessionInfoResponse_VALUE = 156;
    /**
     * <code>k_EGCToGCMsgMasterStartupComplete = 157;</code>
     */
    public static final int k_EGCToGCMsgMasterStartupComplete_VALUE = 157;
    /**
     * <code>k_EMsgGCToGCSOCacheSubscribe = 158;</code>
     */
    public static final int k_EMsgGCToGCSOCacheSubscribe_VALUE = 158;
    /**
     * <code>k_EMsgGCToGCSOCacheUnsubscribe = 159;</code>
     */
    public static final int k_EMsgGCToGCSOCacheUnsubscribe_VALUE = 159;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EGCToGCMsg valueOf(int value) {
      return forNumber(value);
    }

    public static EGCToGCMsg forNumber(int value) {
      switch (value) {
        case 150: return k_EGCToGCMsgMasterAck;
        case 151: return k_EGCToGCMsgMasterAckResponse;
        case 152: return k_EGCToGCMsgRouted;
        case 153: return k_EGCToGCMsgRoutedReply;
        case 154: return k_EMsgGCUpdateSubGCSessionInfo;
        case 155: return k_EMsgGCRequestSubGCSessionInfo;
        case 156: return k_EMsgGCRequestSubGCSessionInfoResponse;
        case 157: return k_EGCToGCMsgMasterStartupComplete;
        case 158: return k_EMsgGCToGCSOCacheSubscribe;
        case 159: return k_EMsgGCToGCSOCacheUnsubscribe;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EGCToGCMsg>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EGCToGCMsg> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EGCToGCMsg>() {
            public EGCToGCMsg findValueByNumber(int number) {
              return EGCToGCMsg.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return in.dragonbra.javasteam.protobufs.tf.Gcsystemmsgs.getDescriptor().getEnumTypes().get(3);
    }

    private static final EGCToGCMsg[] VALUES = values();

    public static EGCToGCMsg valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EGCToGCMsg(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EGCToGCMsg)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022gcsystemmsgs.proto*\357\027\n\014EGCSystemMsg\022\023\n" +
      "\017k_EGCMsgInvalid\020\000\022\021\n\rk_EGCMsgMulti\020\001\022\030\n" +
      "\024k_EGCMsgGenericReply\020\n\022\026\n\022k_EGCMsgSyste" +
      "mBase\0202\022\036\n\032k_EGCMsgAchievementAwarded\0203\022" +
      "\026\n\022k_EGCMsgConCommand\0204\022\030\n\024k_EGCMsgStart" +
      "Playing\0205\022\027\n\023k_EGCMsgStopPlaying\0206\022\033\n\027k_" +
      "EGCMsgStartGameserver\0207\022\032\n\026k_EGCMsgStopG" +
      "ameserver\0208\022\025\n\021k_EGCMsgWGRequest\0209\022\026\n\022k_" +
      "EGCMsgWGResponse\020:\022\"\n\036k_EGCMsgGetUserGam" +
      "eStatsSchema\020;\022*\n&k_EGCMsgGetUserGameSta" +
      "tsSchemaResponse\020<\022\"\n\036k_EGCMsgGetUserSta" +
      "tsDEPRECATED\020=\022 \n\034k_EGCMsgGetUserStatsRe" +
      "sponse\020>\022\032\n\026k_EGCMsgAppInfoUpdated\020?\022\033\n\027" +
      "k_EGCMsgValidateSession\020@\022#\n\037k_EGCMsgVal" +
      "idateSessionResponse\020A\022\"\n\036k_EGCMsgLookup" +
      "AccountFromInput\020B\022\033\n\027k_EGCMsgSendHTTPRe" +
      "quest\020C\022#\n\037k_EGCMsgSendHTTPRequestRespon" +
      "se\020D\022\030\n\024k_EGCMsgPreTestSetup\020E\022\037\n\033k_EGCM" +
      "sgRecordSupportAction\020F\022(\n$k_EGCMsgGetAc" +
      "countDetails_DEPRECATED\020G\022\"\n\036k_EGCMsgRec" +
      "eiveInterAppMessage\020I\022\030\n\024k_EGCMsgFindAcc" +
      "ounts\020J\022\025\n\021k_EGCMsgPostAlert\020K\022\027\n\023k_EGCM" +
      "sgGetLicenses\020L\022\030\n\024k_EGCMsgGetUserStats\020" +
      "M\022\027\n\023k_EGCMsgGetCommands\020N\022\037\n\033k_EGCMsgGe" +
      "tCommandsResponse\020O\022\032\n\026k_EGCMsgAddFreeLi" +
      "cense\020P\022\"\n\036k_EGCMsgAddFreeLicenseRespons" +
      "e\020Q\022\031\n\025k_EGCMsgGetIPLocation\020R\022!\n\035k_EGCM" +
      "sgGetIPLocationResponse\020S\022\035\n\031k_EGCMsgSys" +
      "temStatsSchema\020T\022\032\n\026k_EGCMsgGetSystemSta" +
      "ts\020U\022\"\n\036k_EGCMsgGetSystemStatsResponse\020V" +
      "\022\025\n\021k_EGCMsgSendEmail\020W\022\035\n\031k_EGCMsgSendE" +
      "mailResponse\020X\022\034\n\030k_EGCMsgGetEmailTempla" +
      "te\020Y\022$\n k_EGCMsgGetEmailTemplateResponse" +
      "\020Z\022\032\n\026k_EGCMsgGrantGuestPass\020[\022\"\n\036k_EGCM" +
      "sgGrantGuestPassResponse\020\\\022\035\n\031k_EGCMsgGe" +
      "tAccountDetails\020]\022%\n!k_EGCMsgGetAccountD" +
      "etailsResponse\020^\022\033\n\027k_EGCMsgGetPersonaNa" +
      "mes\020_\022#\n\037k_EGCMsgGetPersonaNamesResponse" +
      "\020`\022\030\n\024k_EGCMsgMultiplexMsg\020a\022$\n k_EGCMsg" +
      "WebAPIRegisterInterfaces\020e\022\034\n\030k_EGCMsgWe" +
      "bAPIJobRequest\020f\022(\n$k_EGCMsgWebAPIJobReq" +
      "uestHttpResponse\020h\022+\n\'k_EGCMsgWebAPIJobR" +
      "equestForwardResponse\020i\022\031\n\024k_EGCMsgMemCa" +
      "chedGet\020\310\001\022!\n\034k_EGCMsgMemCachedGetRespon" +
      "se\020\311\001\022\031\n\024k_EGCMsgMemCachedSet\020\312\001\022\034\n\027k_EG" +
      "CMsgMemCachedDelete\020\313\001\022\033\n\026k_EGCMsgMemCac" +
      "hedStats\020\314\001\022#\n\036k_EGCMsgMemCachedStatsRes" +
      "ponse\020\315\001\022\025\n\020k_EGCMsgSQLStats\020\322\001\022\035\n\030k_EGC" +
      "MsgSQLStatsResponse\020\323\001\022\037\n\032k_EGCMsgMaster" +
      "SetDirectory\020\334\001\022\'\n\"k_EGCMsgMasterSetDire" +
      "ctoryResponse\020\335\001\022#\n\036k_EGCMsgMasterSetWeb" +
      "APIRouting\020\336\001\022+\n&k_EGCMsgMasterSetWebAPI" +
      "RoutingResponse\020\337\001\022&\n!k_EGCMsgMasterSetC" +
      "lientMsgRouting\020\340\001\022.\n)k_EGCMsgMasterSetC" +
      "lientMsgRoutingResponse\020\341\001\022\027\n\022k_EGCMsgSe" +
      "tOptions\020\342\001\022\037\n\032k_EGCMsgSetOptionsRespons" +
      "e\020\343\001\022\030\n\023k_EGCMsgSystemBase2\020\364\003\022#\n\036k_EGCM" +
      "sgGetPurchaseTrustStatus\020\365\003\022+\n&k_EGCMsgG" +
      "etPurchaseTrustStatusResponse\020\366\003\022\032\n\025k_EG" +
      "CMsgUpdateSession\020\367\003\022%\n k_EGCMsgGCAccoun" +
      "tVacStatusChange\020\370\003\022\034\n\027k_EGCMsgCheckFrie" +
      "ndship\020\371\003\022$\n\037k_EGCMsgCheckFriendshipResp" +
      "onse\020\372\003\022\"\n\035k_EGCMsgGetPartnerAccountLink" +
      "\020\373\003\022*\n%k_EGCMsgGetPartnerAccountLinkResp" +
      "onse\020\374\003\022)\n$k_EGCMsgVSReportedSuspiciousA" +
      "ctivity\020\375\003\022(\n#k_EGCMsgAccountTradeBanSta" +
      "tusChange\020\376\003\022$\n\037k_EGCMsgAccountLockStatu" +
      "sChange\020\377\003\022\037\n\032k_EGCMsgDPPartnerMicroTxns" +
      "\020\200\004\022\'\n\"k_EGCMsgDPPartnerMicroTxnsRespons" +
      "e\020\201\004\022\025\n\020k_EGCMsgGetIPASN\020\202\004\022\035\n\030k_EGCMsgG" +
      "etIPASNResponse\020\203\004\022\036\n\031k_EGCMsgGetAppFrie" +
      "ndsList\020\204\004\022&\n!k_EGCMsgGetAppFriendsListR" +
      "esponse\020\205\004\022\"\n\035k_EGCMsgVacVerificationCha" +
      "nge\020\206\004\022%\n k_EGCMsgAccountPhoneNumberChan" +
      "ge\020\207\004\022#\n\036k_EGCMsgAccountTwoFactorChange\020" +
      "\210\004\022 \n\033k_EGCMsgCheckClanMembership\020\211\004\022(\n#" +
      "k_EGCMsgCheckClanMembershipResponse\020\212\004*\225" +
      "\002\n\006ESOMsg\022\023\n\017k_ESOMsg_Create\020\025\022\023\n\017k_ESOM" +
      "sg_Update\020\026\022\024\n\020k_ESOMsg_Destroy\020\027\022\034\n\030k_E" +
      "SOMsg_CacheSubscribed\020\030\022\036\n\032k_ESOMsg_Cach" +
      "eUnsubscribed\020\031\022\033\n\027k_ESOMsg_UpdateMultip" +
      "le\020\032\022#\n\037k_ESOMsg_CacheSubscriptionCheck\020" +
      "\033\022%\n!k_ESOMsg_CacheSubscriptionRefresh\020\034" +
      "\022$\n k_ESOMsg_CacheSubscribedUpToDate\020\035*\353" +
      "\001\n\020EGCBaseClientMsg\022\030\n\023k_EMsgGCPingReque" +
      "st\020\271\027\022\031\n\024k_EMsgGCPingResponse\020\272\027\022\032\n\025k_EM" +
      "sgGCClientWelcome\020\244\037\022\032\n\025k_EMsgGCServerWe" +
      "lcome\020\245\037\022\030\n\023k_EMsgGCClientHello\020\246\037\022\030\n\023k_" +
      "EMsgGCServerHello\020\247\037\022\032\n\025k_EMsgGCClientGo" +
      "odbye\020\250\037\022\032\n\025k_EMsgGCServerGoodbye\020\251\037*\354\002\n" +
      "\nEGCToGCMsg\022\032\n\025k_EGCToGCMsgMasterAck\020\226\001\022" +
      "\"\n\035k_EGCToGCMsgMasterAckResponse\020\227\001\022\027\n\022k" +
      "_EGCToGCMsgRouted\020\230\001\022\034\n\027k_EGCToGCMsgRout" +
      "edReply\020\231\001\022#\n\036k_EMsgGCUpdateSubGCSession" +
      "Info\020\232\001\022$\n\037k_EMsgGCRequestSubGCSessionIn" +
      "fo\020\233\001\022,\n\'k_EMsgGCRequestSubGCSessionInfo" +
      "Response\020\234\001\022&\n!k_EGCToGCMsgMasterStartup" +
      "Complete\020\235\001\022!\n\034k_EMsgGCToGCSOCacheSubscr" +
      "ibe\020\236\001\022#\n\036k_EMsgGCToGCSOCacheUnsubscribe" +
      "\020\237\001B*\n#in.dragonbra.javasteam.protobufs." +
      "tfH\001\200\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
