# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# Artifacts: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

name: Java PR CI/CD

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - 'javasteam-samples/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout JavaSteam with Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Build with Gradle, skip signing
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x signMavenJavaPublication
